// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const wrapper: string;
export const preview: string;
export const hide: string;
export const snap: string;
export const controls: string;
